upgrade to filament v3
awcodes/filament-addons pull request #12
Opened 2023-09-05 05:20 UTC by wilfredchen

2023-09-05 21:38 UTC, awcodes commented
Which elements are you using from this package? This was never released officially.

2023-09-06 03:22 UTC, wilfredchen commented
> Which elements are you using from this package? This was never released officially.

We are using the Heading and DateInput from the package.

2023-09-07 12:52 UTC, awcodes requested changes

2023-09-07 12:52 UTC, awcodes commented on composer.json
> +        "filament/filament": "^3.0-stable",
'-stable' isn't needed here. Please remove.

2023-09-12 12:47 UTC, awcodes approved these changes

2023-09-12 12:47 UTC, merged